version: 2.1
defaults: &defaults
  docker:
    - image: circleci/node:12
jobs:
  run-unit-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install modules
          command: yarn
      - run:
          name: Run unit test
          command: yarn test
workflows:
  workflow:
    jobs:
      - run-unit-test